In [2]:
import numpy as np

In [7]:
#swapaxes
original = np.arange(30).reshape(2,3,5)
print(original)
swapped = np.swapaxes(original,1,2)  #indexes of deimensions
print(swapped)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0  5 10]
  [ 1  6 11]
  [ 2  7 12]
  [ 3  8 13]
  [ 4  9 14]]

 [[15 20 25]
  [16 21 26]
  [17 22 27]
  [18 23 28]
  [19 24 29]]]


In [ ]:
#squeeze
arr=np.arange(20).reshape(1,5,4)
print(arr)
print(arr.shape)
temp =arr.squeeze() #remove 1 dimensions
print(temp,temp.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]
(1, 5, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] (5, 4)
