In [1]:
import numpy as np


In [4]:
one_dim = np.array([1,2,3])
print(one_dim)


[1 2 3]


In [6]:
two_dim = np.array([[1,2,3],[4,5,6]])
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [15]:
zeros= np.zeros((4,3),dtype=int)
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
ones = np.ones((5,6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [18]:
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
custom_diagonal = np.diag([1,2,3,4])
print(custom_diagonal)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
evenly_spaced = np.linspace(5,10,10,endpoint= False)
print(evenly_spaced)

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [32]:
random_values = np.random.randint(1,10,(3,3))
print(random_values)

[[8 1 2]
 [4 3 4]
 [5 3 9]]


In [44]:
floating_random = np.empty((3,3))
print(floating_random)

[[2.0e-323 2.0e-323 2.5e-323]
 [9.9e-324 4.4e-323 3.0e-323]
 [4.4e-323 2.5e-323 2.0e-323]]


In [45]:
shape_arr= np.shape(floating_random)
print(shape_arr)


(3, 3)


In [46]:
dimensions = np.ndim(floating_random)
print(dimensions)

2


In [48]:
size = np.size(floating_random)
print(size)

9


In [51]:
arr= np.arange(10)
arr = np.reshape(arr,(2,5))
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [56]:
arr = np.arange(6).reshape((3,2))
print(arr)
flattened = arr.flatten()
print("flattened =",flattened)

[[0 1]
 [2 3]
 [4 5]]
flattened = [0 1 2 3 4 5]
